export const alphabet = [
  {
    letter: "A",
    image: "/images/a.png",
    audio: "/audio/a.mp3",
    isVowel: true,
  },
  {
    letter: "B",
    image: "/images/b.png",
    audio: "/audio/b.mp3",
    isVowel: false,
  },
  {
    letter: "C",
    image: "/images/c.png",
    audio: "/audio/c.mp3",
    isVowel: false,
  },
  {
    letter: "D",
    image: "/images/d.png",
    audio: "/audio/d.mp3",
    isVowel: false,
  },
  {
    letter: "E",
    image: "/images/e.png",
    audio: "/audio/e.mp3",
    isVowel: true,
  },
  {
    letter: "F",
    image: "/images/f.png",
    audio: "/audio/f.mp3",
    isVowel: false,
  },
  {
    letter: "G",
    image: "/images/g.png",
    audio: "/audio/g.mp3",
    isVowel: false,
  },
  {
    letter: "H",
    image: "/images/h.png",
    audio: "/audio/h.mp3",
    isVowel: false,
  },
  {
    letter: "I",
    image: "/images/i.png",
    audio: "/audio/i.mp3",
    isVowel: true,
  },
  {
    letter: "J",
    image: "/images/j.png",
    audio: "/audio/j.mp3",
    isVowel: false,
  },
  {
    letter: "K",
    image: "/images/k.png",
    audio: "/audio/k.mp3",
    isVowel: false,
  },
  {
    letter: "L",
    image: "/images/l.png",
    audio: "/audio/l.mp3",
    isVowel: false,
  },
  {
    letter: "M",
    image: "/images/m.png",
    audio: "/audio/m.mp3",
    isVowel: false,
  },
  {
    letter: "N",
    image: "/images/n.png",
    audio: "/audio/n.mp3",
    isVowel: false,
  },
  {
    letter: "O",
    image: "/images/o.png",
    audio: "/audio/o.mp3",
    isVowel: true,
  },
  {
    letter: "P",
    image: "/images/p.png",
    audio: "/audio/p.mp3",
    isVowel: false,
  },
  {
    letter: "Q",
    image: "/images/q.png",
    audio: "/audio/q.mp3",
    isVowel: false,
  },
  {
    letter: "R",
    image: "/images/r.png",
    audio: "/audio/r.mp3",
    isVowel: false,
  },
  {
    letter: "S",
    image: "/images/s.png",
    audio: "/audio/s.mp3",
    isVowel: false,
  },
  {
    letter: "T",
    image: "/images/t.png",
    audio: "/audio/t.mp3",
    isVowel: false,
  },
  {
    letter: "U",
    image: "/images/u.png",
    audio: "/audio/u.mp3",
    isVowel: true,
  },
  {
    letter: "V",
    image: "/images/v.png",
    audio: "/audio/v.mp3",
    isVowel: false,
  },
  {
    letter: "W",
    image: "/images/w.png",
    audio: "/audio/w.mp3",
    isVowel: false,
  },
  {
    letter: "X",
    image: "/images/x.png",
    audio: "/audio/x.mp3",
    isVowel: false,
  },
  {
    letter: "Y",
    image: "/images/y.png",
    audio: "/audio/y.mp3",
    isVowel: false,
  },
  {
    letter: "Z",
    image: "/images/z.png",
    audio: "/audio/z.mp3",
    isVowel: false,
  },
];