export const alphabet = [
  { letter: "A", animal: "Alpaca", image: "img/A.png", animalImage: "img/ALPACA.png", audio: "audio/a.mp3", isVowel: true },
  { letter: "B", animal: "Ballena", image: "img/B.png", animalImage: "img/BALLENA.png", audio: "audio/b.mp3", isVowel: false },
  { letter: "C", animal: "Canguro", image: "img/C.png", animalImage: "img/CANGURO.png", audio: "audio/c.mp3", isVowel: false },
  { letter: "D", animal: "Delfín", image: "img/D.png", animalImage: "img/DELFIN.png", audio: "audio/d.mp3", isVowel: false },
  { letter: "E", animal: "Elefante", image: "img/E.png", animalImage: "img/ELEFANTE.png", audio: "audio/e.mp3", isVowel: true },
  { letter: "F", animal: "Flamenco", image: "img/F.png", animalImage: "img/FLAMENCO.png", audio: "audio/f.mp3", isVowel: false },
  { letter: "G", animal: "Gato", image: "img/G.png", animalImage: "img/GATO.png", audio: "audio/g.mp3", isVowel: false },
  { letter: "H", animal: "Hipopótamo", image: "img/H.png", animalImage: "img/HIPOPOTAMO.png", audio: "audio/h.mp3", isVowel: false },
  { letter: "I", animal: "Iguana", image: "img/I.png", animalImage: "img/IGUANA.png", audio: "audio/i.mp3", isVowel: true },
  { letter: "J", animal: "Jirafa", image: "img/J.png", animalImage: "img/JIRAFA.png", audio: "audio/j.mp3", isVowel: false },
  { letter: "K", animal: "Koala", image: "img/K.png", animalImage: "img/KOALA.png", audio: "audio/k.mp3", isVowel: false },
  { letter: "L", animal: "León", image: "img/L.png", animalImage: "img/LEON.png", audio: "audio/l.mp3", isVowel: false },
  { letter: "M", animal: "Mono", image: "img/M.png", animalImage: "img/MONO.png", audio: "audio/m.mp3", isVowel: false },
  { letter: "N", animal: "Nutria", image: "img/N.png", animalImage: "img/NUTRIA.png", audio: "audio/n.mp3", isVowel: false },
  { letter: "O", animal: "Oso", image: "img/O.png", animalImage: "img/OSO.png", audio: "audio/o.mp3", isVowel: true },
  { letter: "P", animal: "Pez", image: "img/P.png", animalImage: "img/PEZ.png", audio: "audio/p.mp3", isVowel: false },
  { letter: "Q", animal: "Quetzal", image: "img/Q.png", animalImage: "img/QUETZAL.png", audio: "audio/q.mp3", isVowel: false },
  { letter: "R", animal: "Rinoceronte", image: "img/R.png", animalImage: "img/RINOSERONTE.png", audio: "audio/r.mp3", isVowel: false },
  { letter: "S", animal: "Serpiente", image: "img/S.png", animalImage: "img/SERPIENTE.png", audio: "audio/s.mp3", isVowel: false },
  { letter: "T", animal: "Tigre", image: "img/T.png", animalImage: "img/TIGRE.png", audio: "audio/t.mp3", isVowel: false },
  { letter: "U", animal: "Unicornio", image: "img/U.png", animalImage: "img/UNICORNIO.png", audio: "audio/u.mp3", isVowel: true },
  { letter: "V", animal: "Vaca", image: "img/V.png", animalImage: "img/VACA.png", audio: "audio/v.mp3", isVowel: false },
  { letter: "W", animal: "Wey", image: "img/W.png", animalImage: "img/WEY.png", audio: "audio/w.mp3", isVowel: false },
  { letter: "X", animal: "Xero", image: "img/X.png", animalImage: "img/XERO.png", audio: "audio/x.mp3", isVowel: false },
  { letter: "Y", animal: "Yegua", image: "img/Y.png", animalImage: "img/YEGUA.png", audio: "audio/y.mp3", isVowel: false },
  { letter: "Z", animal: "Zebra", image: "img/Z.png", animalImage: "img/ZEBRA.png", audio: "audio/z.mp3", isVowel: false },
];