export const alphabet = [
  { letter: "A", image: "img/A.png", audio: "audio/a.mp3", isVowel: true },
  { letter: "B", image: "img/B.png", audio: "audio/b.mp3", isVowel: false },
  { letter: "C", image: "img/C.png", audio: "audio/c.mp3", isVowel: false },
  { letter: "D", image: "img/D.png", audio: "audio/d.mp3", isVowel: false },
  { letter: "E", image: "img/E.png", audio: "audio/e.mp3", isVowel: true },
  { letter: "F", image: "img/F.png", audio: "audio/f.mp3", isVowel: false },
  { letter: "G", image: "img/G.png", audio: "audio/g.mp3", isVowel: false },
  { letter: "H", image: "img/H.png", audio: "audio/h.mp3", isVowel: false },
  { letter: "I", image: "img/I.png", audio: "audio/i.mp3", isVowel: true },
  { letter: "J", image: "img/J.png", audio: "audio/j.mp3", isVowel: false },
  { letter: "K", image: "img/K.png", audio: "audio/k.mp3", isVowel: false },
  { letter: "L", image: "img/L.png", audio: "audio/l.mp3", isVowel: false },
  { letter: "M", image: "img/M.png", audio: "audio/m.mp3", isVowel: false },
  { letter: "N", image: "img/N.png", audio: "audio/n.mp3", isVowel: false },
  { letter: "O", image: "img/O.png", audio: "audio/o.mp3", isVowel: true },
  { letter: "P", image: "img/P.png", audio: "audio/p.mp3", isVowel: false },
  { letter: "Q", image: "img/Q.png", audio: "audio/q.mp3", isVowel: false },
  { letter: "R", image: "img/R.png", audio: "audio/r.mp3", isVowel: false },
  { letter: "S", image: "img/S.png", audio: "audio/s.mp3", isVowel: false },
  { letter: "T", image: "img/T.png", audio: "audio/t.mp3", isVowel: false },
  { letter: "U", image: "img/U.png", audio: "audio/u.mp3", isVowel: true },
  { letter: "V", image: "img/V.png", audio: "audio/v.mp3", isVowel: false },
  { letter: "W", image: "img/W.png", audio: "audio/w.mp3", isVowel: false },
  { letter: "X", image: "img/X.png", audio: "audio/x.mp3", isVowel: false },
  { letter: "Y", image: "img/Y.png", audio: "audio/y.mp3", isVowel: false },
  { letter: "Z", image: "img/Z.png", audio: "audio/z.mp3", isVowel: false },
];